#include <iostream>
#include <vector>
#include <string>
#include "cue_cards.h"
#include "continue.h"

using std::cin, std::cout, std::string, std::vector, std::pair;

const vector<pair<string, string>> cueCards = {
    {"What is a pure substance?", "A pure substance contains only one type of particle. These particles can be molecules or atoms. For example, oxygen and water are both pure substances."},
    {"What is a mixture?", "A mixture contains more than one pure substance mixed together. Examples of mixtures include salt water and steel"},
    {"What is an element?", "An element is a substance containing only one kind of atom. Examples of elements include gold and hydrogen."},
    {"What is a molecule?", "A molecule is a particle with more than one type of atom. Example of molecules include table salt and water."},
    {"What is a homogeneous mixture?", "A homogeneous mixture is one where you cannot tell the constituent substances apart. It has one phase (appearance). Examples of homogeneous mixtures include chocolate milk and salt water"},
    {"What is a heterogeneous mixture?", "A heterogeneous mixture is one where you can tell the constituent substances apart. It has more than one phase (appearance). Examples of heterogeneous mixtures include water + oil and chocolate chip cookie batter"},
    {"What is filtration?", "Filtration is separation of a heterogeneous mixture (solid & liquid) by filtering particles by size, weight, etc. For example, you can filter sand and water"},
    {"What is evaporation?", "Evaporation is heating up a liquid until it evaporates, leaving behind residue. For example, you can get salt from saltwater by evaporating the water."},
    {"What is distillation?", "Distillation is heating up a liquid until it evaporates, leaving behind residue, and condensing the evaporated liquid. For example, you can separate water and salt through distillation."},
    {"What is separation?", "Separation occurs when two substances have different densities, so they naturally separate on their own. A separatory funnel may be used to drain one substance. For example, you can separate water and oil."},
    {"What is chromatography?", "Chromatography utilises a solvent. Substances are separated based off their solubility in the solvent."},
    {"What are 2 indicators of a pure substance?", "Narrow, high melting point (higher than impure substance) and low separation in chromatography"},
    {"What is the difference between boiling and evaporation?", "Boiling occurs at boiling point and occurs throughout the liquid. Evaporation occurs only at the surface and happens at various temperatures"},
    {"What are the 4 parts of the Kinetic Molecular Theory?", "All matter is made up of small particles.\nThese particles have kinetic energy.\n Kinetic energy is proportional to temperature and magnitude of motion.\nCollisions between particles are elastic (no loss in kinetic energy)"},
    {"What is the difference between kinetic energy, temperature, and heat?", "Kinetic energy is energy relating to movement.\nTemperature is the average kinetic energy.\nHeat is the amount of thermal energy a substance is transferring to its environment"},
    {"What is the difference between Kelvin and Celsius?", "Kelvin and Celsius follow the same scale, but Kelvin is 273 degrees higher (to get to Kelvin from Celsius, add 273)"},
    {"What are the relative masses of the proton, neutron, and electron?", "1, 1, and 1/2000"},
    {"What is the difference between relative atomic mass and mass number?", "Mass number is the mass of one specific isotope of an element.\nRelative atomic mass is the weighted average of all isotopes of an element."},
    {"What happens when you change the number of protons in an element?", "It becomes a different element"},
    {"What happens when you change the number of neutrons in an element?", "It becomes a different isotopes. Different isotopes have different physical properties but similar chemical properties\nUnstable isotopes can undergo radioactive decay"},
    {"What happens when you change the number of electrons in an element?", "It becomes a different ion. Different ions have similar physical properties and different chemical properties (reactivity changes)"},
    {"What does mass spectrometry separate ions by?", "Mass/charge ratio"},
    {"What is the difference between an energy level, a sublevel, and an orbital?", "An energy level contains multiple sublevels. They correspond to the shells in a Bohr diagram\nA subshell contains multiple orbitals and are classified by s, p, d, or f. Depending on their classification, they can hold 2, 6, 10, or 14 electrons\nAn orbital can hold up to 2 electrons with opposite spin"},
    {"What is an atoms ground state?", "Arrangement of electrons with the lowest energy"},
    {"What is an atoms excited state?", "Any electron configuration other than the ground state"},
    {"What is ionization energy?", "The amount of energy it takes to ionize an electron (bring it to energy level infinity where it leaves the atom)\nAtoms are exposed to specific wavelengths of light which excite the electrons away from the atom"},
    {"What are some factors that can affect ionization energy?", "Atoms with more energy levels have lower ionization energies because the electrons are further from the nucleus and experience less electrostatic attraction\nAtoms with more protons have higher ionization energies because there is more positive charge to attract the electrons"},
    {"How does ionization energy change across groups and periods?", "IE drops sharpy when moving to a new period (new energy level, less attraction)\nIE increases gradually across a period (more protons, stronger attraction)\nIE jumps down from half filled/fully filled sublevel (stable configuration, easy to reach)"},
    {"How does ionization energy change as you remove more and more electrons?", "It strictly increases. There are less electrons for the protons to attract so they experience stronger attraction and require more energy to overcome electrostatic attraction"},
    {"Distinguish between the following terms:\nStandard solution\nStandardization of a solution\nStock solution\nSerial dilution", "Standard solution - a solution with an accurate, known percentage\nStandardization - process of testing to make sure a solution has accurate and precise concentration\nStock solution - a highly concentrated solution which is diluted before use\nSerial dilution - process of diluting a concentrated solution across several steps"},
    {"What is an ideal gas?", "An ideal gas is a theoretical gas which behaves according to the ideal gas law\nThe ideal gas model assumes that gas particles have negligible volume and never collide with one another and experience 0 intermolecular forces"},
    {"Under which conditions do regular gases behave most like ideal gases?", "Under high temperature and low pressure\nHigh temperatures reduce intermolecular forces while low pressure reduces volume of gas particles"},
    {"What is Avogadro's law of gases?", "Under constant temperature, volume is proportional to the number of particles"},
    {"What is the combined gas law?", "The combined gas law states that, when the number of moles of a gas is constant, PV/T is constant where\nP is pressure\nV is volume\nT is temperature"},
    {"What is the definition of gas pressure?", "The pressure of a gas is defined as the frequency of collisions between gas particles and the sides of its container"},
    {"What is the difference between nuclear charge and effective charge?", "Nuclear charge is the number of protons in the nucleus of an atom\nIn order for the atom to lose electrons, the electrostatic attraction between the protons and the electrons must be overcome\nEffective charge is the amount of change an atom has when forming an ion\nEffective charge is equal to the nuclear charge minus the number of non-valence electrons (e.g. Na has 1+ effective charge)"},
    {"What factors affect the strength of an ionic bond?", "Smaller ionic radii result in stronger bonds\nGreater ionic charge results in stronger bonds"},
    {"Why are transition metals multivalent? Why is zinc not a transition metal?", "Transition metals are able to lose electrons in their d orbitals to use in bonding\nSince the s and d orbitals are similar in energy, they are both used in bonding\nZinc is not multivalent due to a full s and d orbital, making it difficult to remove electrons from its d orbital"},
    {"What is the difference between anions and cations?", "Anions are negative (anions -> onions make you cry)\nCations are positive (think pawsitive uwu)"},
    {"What is lattice enthalpy?", "Lattice enthalpy is the amount of energy required to vaporize one mole of an ionic compound\nStronger ionic bonds result in higher lattice enthalpy"},
    {"What is the structure of ionic compounds? What physical properties does it explain?", "Ionic compounds form repeating crystal lattices\nThe strong electromagnetic attraction between the ions describe the compounds hardness, but also its brittleness as one small slip can cause the ions to misalign and repel\nDue to the strong nature of ionic bonds, ionic compounds typically have very high melting points and low volatility\nThe charged ions are frequently soluble in polar solvents such as water (note: salts with very strong electromagnetic attraction are not soluble in water)\nAqueous ionic compounds conduct electricity due to the mobile ions' ability to carry charge"},
    {"Describe the features of the metallic bonding model and how they explain the physical properties of metals", "Since metals have low electronegativity, they don't hold on to their electrons very well\nWhen metals bond, the valence electrons leave the nucleus, leaving a crystal lattice of cations surrounded by a sea of delocalized electrons\nThe electrostatic attraction between the electrons and the cations keeps the metal intact\nThe mobil delocalized electrons can carry thermal and electrical energy, explaining the excellent thermal and electrical conductivity of many metals\nSince the cations aren't bound in place, metals are often malleable and ductile"},
    {"Why do transition metals frequently conduct electricity better than s and p block metals?", "Transition metals have more electrons to release from their d orbitals, leading to a denser sea of electrons and more effective charge transfer"},
    {"What factors affect the strength of metallic bonds?", "Metals with more protons/electrons have stronger bonds due to stronger electrostatic attraction\nLarger atoms have weaker bonds due to increased electron shielding from their numerous electron shells"},
    {"What are the two types of alloys? How can alloys increase the strength of a metal?", "Interstitial alloys insert small metals between the gaps of larger ones\nSubstitutional alloys replace some metal cation with other ones of similar size\nAlloying can increase the strength of a metal by disrupting the perfect crystal lattice, leading to more resistance in sliding the lattice layers over each other"},
    {"Describe the model of covalent bonding. Why are covalent bonds weaker than metallic or ionic bonds?", "Covalent bonds form through orbital overlaps. Electrons have a higher probability to exist in the overlap region\nEach bond consists of an electron pair which electrostatically attracts the two nuclei of the atoms in the bonds\nSince the atoms are each attracted to two electrons, the electrostatic attraction in a covalent bond is weaker than that of ionic or metallic bonding"},
    {"Using electrostatic repulsion and attraction, explain covalent bond lengths", "When atoms are too far, they experience little attraction\nWhen atoms are too close together, they experience too much electrostatic repulsion\nThe balance between electrostatic attraction and repulsion results in the different bond lengths"},
    {"Why do covalent compounds have lower melting points than ionic compounds?", "Melting ionic compounds involves breaking the ionic bond, which requires a lot of energy\nMelting covalent compounds only requires breaking intermolecular forces, which are much weaker"},
    {"Name the 3 exceptions on the periodic table which fill their valence shell with less than 8 electrons", "Hydrogen has full valence with 2 electrons\nBeryllium has full valence with 4 electrons\nBoron has full valence with 6 electrons"},
    {"What is a coordination bond? How can they be marked on Lewis diagrams? Why are they usually not?", "Coordination bonds occur when both electrons in a covalent bond come from one atom\nCoordination bonds are denoted by an arrow pointing from the donor atom to the recipient atom\nAfter coordination bonds form, they function identically to a regular covalent bond, hence they are not usually marked"},
    {"How is formal charge calculated?", "# of valence e's in unbonded atom - # of lone electrons in bonded atom - half of # of bonded electrons in bonded atom\nCan be simplified to original e's - number of bonds - # of e's left"},
    {"How is formal charge used to determine the optimal Lewis structure?", "The optimal formal charge contains lowest net charge, lowest number of charged atoms, lowest charge on those atoms, and the negative charges on the more electronegative atoms"},
    {"What are resonance structures/resonance hybrids?", "Resonance structures are multiple different valid Lewis structures for the same molecule\nA resonance hybrid of that molecule is a total representation of all possible structures of that molecule (think delocalisation of electrons in carbonate)"},
    {"Give 4 pieces of evidence suggesting why benzene does not follow the Kekule model/experiences resonance", "1. All C-C bonds in benzene have equal length\nThis means that all C-C bonds in benzene should experience resonance\n2. Benzene is more stable than Kekule's model predicts\nThe resonance in benzene keeps the electrons evenly distributed, keeping it stable\n3. Benzene rarely undergoes addition reactions, more likely to undergo substitution reactions\nAddition reactions disrupt benzene's ring of delocalised electrons\n4. There are only 3 isomers of dibromobenzene\nThis suggests high levels of symmetry in benzene, something not observed in Kekule's model"},
    {"Compare and contrast the molecular geometry, structure, hardness, electrical conductivity, and its reason in the following allotropes: graphite, graphene, diamond, fullerenes, nanotubes", R"(Name       Geometry         Structure     Hardness       Conductivity
Graphite   Trigonal planar  Sheets        Soft           Very good
Graphene   Trigonal planar  Sheet         Soft           Very good
Diamond    Tetrahedral      Solid crystal Hard           Poor
Fullerenes In between       Balls         Slippery       Poor
Nanotubes  Trigonal planar  Hollow tube   Extremely hard Very good)"},
    {"What are the 4 types of intermolecular forces? When do they occur? Which ones are stronger/weakest?", "The 4 intermolecular forces in order of increasing strength are:\nLondon dispersion forces -> dipole-induced dipole -> dipole-dipole -> hydrogen bonding\nLondon dispersion forces occur because electron positions are probabilistic and may randomly result in a more charge-dense side of the molecule, charging the molecule and creating attraction between the molecules\nDipole-induced dipole attraction occurs when a polar molecule approaches a non-polar molecule, inducing a temporary dipole on the non-polar molecule\nDipole-dipole attraction occurs when two polar molecules attract due to opposite dipole charges attracting\nHydrogen bonding occurs when hydrogen is bound to fluorine, oxygen, or nitrogen, which \"steal\" the hydrogen's electrons, creating a very strong charge which can form attraction with other charged molecules"},
    {"How can intermolecular forces be used to compare melting/boiling points of two compounds?", "The most dominant intermolecular force creates the strongest intermolecular attraction, increasing melting & boiling points (molecules which experience hydrogen bonding often have higher boiling points than molecules who don't)"}
};

void pickCueCard() {
    cout << "Cue Card\n";
    int card = rand() % cueCards.size();
    cout << cueCards[card].first << "\n";
    next();
    cout << cueCards[card].second << '\n';
}
